# Generated by Django 2.2.10 on 2020-05-11 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_likes', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_likes', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'ordering': ('-id',),
            },
        ),
    ]
