# Generated by Django 2.2.10 on 2020-05-14 16:21

import common.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='added',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=common.utils.get_file_upload_path, verbose_name='image file'),
        ),
    ]
